name: Checkout branch

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup github actor
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: checkout to update branch
        run: |
          git switch test-branch || git switch -c test-branch
      - name: commit
        run: |
          git commit -m "test" --allow-empty
          git push origin test-branch
      - name: create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh pr create --title "test pr" --body "body" --base main --head test-branch
