name: Tag commit

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: What environment to deploy to
        required: true
        options:
          - dev
          - qa
          - uat
          - prod
      application:
        type: choice
        description: Which app to deploy
        required: true
        options:
          - app1
          - app2
          - app3

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tags
        if: ${{ github.event.inputs.environment == 'prod' }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          TAG_NAME="release/${{ github.event.inputs.application }}-$(git rev-parse --short HEAD)"
          LATEST_TAG_NAME="release/${{ github.event.inputs.application }}-latest"

          if [ $(git tag -l "${TAG_NAME}") ]; then
            echo "${TAG_NAME} already exists, skipping"
          else
            git tag -a "${TAG_NAME}" -m "Release ${{ github.events.inputs.application }} on $(date "+%Y-%m-%d") from $(git rev-parse --short HEAD)"
            git push origin "${TAG_NAME}"
          fi

          git tag "${LATEST_TAG_NAME}"
          git push origin "${LATEST_TAG_NAME}" --force
